### ISSUE TITLE
Error Parsing YouTube page for Unlisted video

### ISSUE THREAD

**Issue by amhed** [flagbug/YoutubeExtractor#139]
"Could not parse the Youtube page for URL http://youtube.com/watch?v=VGZ1Qhx0I4U 
This may be due to a change of the Youtube page structure."

*StackTrace*

```
at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
```

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151
