### ISSUE TITLE
Could not parse the Youtube page for URL http://youtube.com/watch?v=HcXNPI-IPPM

### ISSUE THREAD

**Issue by lkrammes** [flagbug/YoutubeExtractor#279]
YoutubeExtractor.YoutubeParseException: Could not parse the Youtube page for URL http://youtube.com/watch?v=HcXNPI-IPPM
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues ---> System.NotSupportedException: Result cannot be called on a failed Match.
   at System.Text.RegularExpressions.Match.Result(String replacement)
   at YoutubeExtractor.DownloadUrlResolver.LoadJson(String url) in DownloadUrlResolver.cs:line 315
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature) in DownloadUrlResolver.cs:line 88
   --- End of inner exception stack trace ---
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl) in DownloadUrlResolver.cs:line 322
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature) in DownloadUrlResolver.cs:line 118

**Comment by BalaFFS** [comment]
I also have the same issue. 
I am trying to download my personal uploads. 
The problem is the following. If the video is private, I get the error you get. If then I change the video to public, all works fine and the video is downloading. Any way to solve this?
Also, videos marked as unlisted work fine. Only the private ones don't work.

Edit:

I know it's a stupid remark, as there is no point in trying to download something you don't see, and you can download your own videos from youtube itself, but it would be nice to be able to integrate this tool somewhere else, where you need to download all your vid's.
