### ISSUE TITLE
YoutubeExtractor.YoutubeParseException

### ISSUE THREAD

**Issue by W4RP1G369** [flagbug/YoutubeExtractor#299]
I am getting this issue when I try to use the YouTube Extractor for Slam: 

> YoutubeExtractor.YoutubeParseException: Could not parse the Youtube page for URL http://youtube.com/watch?v=idPqijh2EWk
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues ---> System.NotSupportedException: Result cannot be called on a failed Match.
   at System.Text.RegularExpressions.Match.Result(String replacement)
   at YoutubeExtractor.DownloadUrlResolver.GetHtml5PlayerVersion(JObject json)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   --- End of inner exception stack trace ---
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e)

Please help.

**Comment by okutbay** [comment]
Having the same issue, it ran in the first try but later started to get this exception. I did not get what is wrong. 

YoutubeExtractor.YoutubeParseException
  HResult=0x80131500
  Message=Could not parse the Youtube page for URL http://youtube.com/watch?v=Mus0XbaGx0M
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues
  Source=YoutubeExtractor
  StackTrace:
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   at MP3Head.App.Program.Main(String[] args) in C:\Sources\MP3Head\MP3Head.App\Program.cs:line 28

Inner Exception 1:
NotSupportedException: Result cannot be called on a failed Match.
