### ISSUE TITLE
YouTube Import Issues (YoutubeParseException)

### ISSUE THREAD

**Issue by HDFlood** [flagbug/YoutubeExtractor#327]
Having a bit of difficulties loading YouTube imports into SLAM. I've had this issue only recently.  The consistent error seems to be __YoutubeExtractor.YoutubeParseException__. Examples:

```
--------------------18/11/2018 06:18:44 UTC--------------------
YoutubeExtractor.YoutubeParseException: Could not parse the Youtube page for URL http://youtube.com/watch?v=VnWEMCvlHck
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues ---> System.NotSupportedException: Result cannot be called on a failed Match.
   at System.Text.RegularExpressions.Match.Result(String replacement)
   at YoutubeExtractor.DownloadUrlResolver.GetHtml5PlayerVersion(JObject json)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   --- End of inner exception stack trace ---
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e)
```

```
--------------------18/11/2018 06:24:16 UTC--------------------
YoutubeExtractor.YoutubeParseException: Could not parse the Youtube page for URL http://youtube.com/watch?v=N8nGig78lNs
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues ---> System.NotSupportedException: Result cannot be called on a failed Match.
   at System.Text.RegularExpressions.Match.Result(String replacement)
   at YoutubeExtractor.DownloadUrlResolver.GetHtml5PlayerVersion(JObject json)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   --- End of inner exception stack trace ---
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e)
```

Like I said, I've only started getting this issue recently. Any feedback, help and/or redirects would be greatly appreciated.

**Comment by anilgit90** [comment]
Please look at pull request #333 , I hope it will solve your problems.
