### ISSUE TITLE
Youtube Extractor

### ISSUE THREAD

**Issue by SellabA** [flagbug/YoutubeExtractor#361]
System.NotSupportedException: Result cannot be called on a failed Match.
   at System.Text.RegularExpressions.Match.Result(String replacement)
   at YoutubeExtractor.DownloadUrlResolver.GetHtml5PlayerVersion(JObject json)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   --- End of inner exception stack trace ---
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by Shurik96** [comment]
UNABLE TO PLAY VIDEO Hiya! Could not parse the Youtube page for URL http://youtube.com/watch?v5UoDP Mij4k This may be due to a change of the Youtube page structure.

**Comment by janakiram-a** [comment]
I am also facing the same issue, please anyone help us in resolving the issue.

**Comment by matt4499** [comment]
Could not parse the Youtube page for URL http://youtube.com/watch?v=HSijJun96-8
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues
